### PR TITLE
Adds a checkFullPath option

### PR DESCRIPTION
**Pull request by luislobo**
Adds a checkFullPath option so you can force the full path to be checked, in the cases where you have something like admin -> user -> conditional() -> action

### CODE REVIEW

**Comment by ramniquesingh** [comment]
@luislobo sorry for the late reply. Can you provide an access check case where a full path check is required?

**Comment by luislobo** [comment]
I don't remember right now the use case but I think it was this one:
[
    // anonymous user calls
    {a: 'anonymous', can: 'show login'},
    {a: 'anonymous', can: 'logout'},
    {a: 'normal', can: 'anonymous'},
    {a: 'normal', can: 'use application'},
    {a: 'normal', can: 'get dashboard',
      when: function(params, next) {
        RbacService.canViewDashboard(params, next);
      }},
    {a: 'admin', can: 'normal'},
  ]

If an admin wants to get dashboard, the condition was not being validated, while it needed to be validated.

**Comment by luislobo** [comment]
Actually I checked your docs: in my case, the full path needs to be checked:

In your docs you say:

The following path is checked:

'admin' --> 'user' --> 'editor' [conditional] --> 'edit posts'

To go from 'admin' to 'user', there is no condition. So the rest of the path is considered to be checked AND successful.

In my case, I need the admin conditions to be checked, as in my conditions, I check that you are retrieving objects that belong to your organization. So, it should reject access to that if the user is trying to access data that they should not have access to.

That way, I can centralize and have a cross check for all data in one single service, instead of distributing that check on all my controller's actions.

**Comment by aldelucca1** [comment]
+1

**Comment by conradoqg** [comment]
+1

**Pull request merged**
